# Generated by Django 3.0.4 on 2020-12-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_id', models.BigIntegerField()),
                ('run_start_date', models.DateTimeField()),
                ('result', models.CharField(max_length=100)),
                ('block_no', models.BigIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('offpoint_category', models.CharField(blank=True, max_length=100, null=True)),
                ('offpoint', models.BigIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('measurement_base_time', models.DateTimeField(blank=True, null=True)),
                ('evaluation_place', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ana_summary',
                'managed': False,
            },
        ),
    ]
